const Screens = {
    HOME_SCREEN_BOTTOM: 'HOME_SCREEN_BOTTOM',
    HOME_SCREEN: 'HOME_SCREEN',
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    NEWS_FEED: 'NEWS_FEED',
    PRIVATE_CHAT: 'PRIVATE_CHAT',
    CREATE_NEWS: 'CREATE_NEWS',
    ALL_MESSAGES: 'ALL_MESSAGES',
    SETTINGS: 'SETTINGS',
    USER_PROFILE: 'USER_PROFILE',
    MY_AREA: 'MY_AREA',
    DASHBOARD_SCREENS: 'DASHBOARD_SCREENS',
}

export default Screens